### PR TITLE
deployed podAntiAffinity

### PR DESCRIPTION
**Pull request by symanovich-a**
This settings to restrict lotus nodes on single worker node.

### CODE REVIEW

**Comment by symanovich-a** [comment]
https://github.com/protofire/Filecoin-node-hosting-management/issues/87

**Comment by ArseniiPetrovich** [comment]
Please, rename affinity variable to antiaffinity for better naming

**Review by ArseniiPetrovich — CHANGES_REQUESTED** [review]
See above

**Comment by symanovich-a** [comment]
@ArseniiPetrovich check, please

**Comment by ArseniiPetrovich** [comment]
LGTM

**Review by ArseniiPetrovich — APPROVED** [review]
+

**Pull request merged**
